name: qrify_me
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  intl: ^0.18.1
  data_table_2: ^2.5.0
  google_maps_flutter: ^2.2.8
  geocoding: ^2.1.0
  location: ^4.4.0
  geolocator: ^9.0.2
  lottie: ^2.3.2
  qr_flutter: ^4.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.1
  razorpay_flutter: ^1.3.5
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
