// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLHBOysEi7XQSndXCFjV11w7X6we-jrU',
    appId: '1:806661858577:web:10f429f328f0a8f6da58b0',
    messagingSenderId: '806661858577',
    projectId: 'qrifyme-e7e86',
    authDomain: 'qrifyme-e7e86.firebaseapp.com',
    storageBucket: 'qrifyme-e7e86.appspot.com',
    measurementId: 'G-72GEBR97WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9eFW1MsBpYzc-2RaojnSXVghKVNDG22M',
    appId: '1:806661858577:android:85bc0bc0255bba4bda58b0',
    messagingSenderId: '806661858577',
    projectId: 'qrifyme-e7e86',
    storageBucket: 'qrifyme-e7e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFoOf6LeodlZJZFxeMLsGISCu8QA6jsw0',
    appId: '1:806661858577:ios:36f40ea4b4d56a48da58b0',
    messagingSenderId: '806661858577',
    projectId: 'qrifyme-e7e86',
    storageBucket: 'qrifyme-e7e86.appspot.com',
    androidClientId: '806661858577-0q6941adhe2j2kunl0bm53001p77nm0j.apps.googleusercontent.com',
    iosClientId: '806661858577-bhslm3rslseoh3rrjmkcrkl2q3u9ds6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrifyMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFoOf6LeodlZJZFxeMLsGISCu8QA6jsw0',
    appId: '1:806661858577:ios:e811439f25119485da58b0',
    messagingSenderId: '806661858577',
    projectId: 'qrifyme-e7e86',
    storageBucket: 'qrifyme-e7e86.appspot.com',
    androidClientId: '806661858577-0q6941adhe2j2kunl0bm53001p77nm0j.apps.googleusercontent.com',
    iosClientId: '806661858577-dhatkqa1s3cc382vkjr6dr5ngg06se3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrifyMe.RunnerTests',
  );
}
